# Project language.
language: python

# Supported Python version.
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Install dependencies.
install:
  - "pip install requests"
  - "python setup.py install"

# Run tests.
script:
  - "cd test"
  - "bash run.sh"
