# Project language.
language: python

# Supported Python version.
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# Install dependencies.
install:
  - "pip install lxml requests"
  - "python setup.py install"

# Run tests.
script:
  - "cd test"
  - "bash run.sh"
